function data = importfile(filename)
%IMPORTFILE Import data from a text file
%  V0 = IMPORTFILE(FILENAME) reads data from text file FILENAME for the
%  default selection.  Returns the data as a table.
%
%  V0 = IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  V0 = importfile("/Users/thomastiotto/PycharmProjects/memristor_models/data/Radius 10 um/-2V_0.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 19-Jul-2021 16:24:46

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 1
    filename = "Radius 10 um/-2V_0.csv";
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 5);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "T", "V", "I", "R"];
opts.SelectedVariableNames = ["T", "V", "I", "R"];
opts.VariableTypes = ["string", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Var1", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Var1", "EmptyFieldRule", "auto");

% Import the data
data = readtable(strcat("../data/",filename), opts);

end